import assert from 'node:assert/strict';
import { auth } from '../server/auth.js';
import { community } from '../server/community.js';
import { createDB, request, call, register } from './account-support.js';

const DB = createDB(), env = { DB }, alice = await register(auth, env, 'Alice Dragon', 'alice@example.com'), bob = await register(auth, env, 'Bob Dragon', 'bob@example.com');
const item = { id: 'local:dragon', title: 'Dragon <b>Chronicles</b>', kind: 'manhwa', coverUrl: '/assets/dragon-cover.svg', provider: 'local', originLanguage: 'en', description: '<script>not stored</script>', malicious: 'not stored' };
const post = (path, data, account = alice) => call(community, request(path, { method: 'POST', cookie: account.cookie, data }), env);
const get = (path, account) => call(community, request(path, { cookie: account?.cookie }), env);
assert.equal((await get('/api/library')).status, 401);
assert.equal((await post('/api/library', { mediaId: item.id, kind: 'favorite', item, userId: bob.user.id })).status, 200);
assert.equal((await post('/api/library', { mediaId: item.id, kind: 'reading', item })).status, 200);
assert.equal((await post('/api/library', { mediaId: item.id, kind: 'completed' })).status, 200);
const library = await (await get('/api/library', alice)).json();
assert.deepEqual(library.items.map(entry => entry.kind).sort(), ['completed', 'favorite']); assert.equal(library.items[0].item.title, 'Dragon Chronicles'); assert.equal(library.items[0].item.malicious, undefined); assert.equal(library.items[0].item.description, undefined);
assert.deepEqual((await (await get('/api/library', bob)).json()).items, []);
assert.equal((await post('/api/library', { mediaId: 'local:dragon', kind: 'favorite', item: { ...item, coverUrl: 'javascript:alert(1)' } })).status, 400);
assert.equal((await post('/api/library', { mediaId: 'local:dragon', kind: 'favorite', item: { ...item, id: 'local:other' } })).status, 400);
assert.equal((await post('/api/library', { mediaId: '123', kind: 'favorite', item })).status, 400);
assert.equal((await post('/api/library', { mediaId: item.id, kind: 'favorite', remove: true })).status, 200);
console.log('PASS: user-scoped real library, independent favorite/status, metadata whitelist, unsafe URL/ID rejection');

const progress = { mediaId: item.id, chapterId: 'local:dragon:chapter-1', page: 8, totalPages: 10, percent: 80, item };
assert.equal((await post('/api/progress', progress)).status, 200);
assert.equal((await post('/api/progress', { ...progress, percent: 100, page: 10 })).status, 200);
assert.equal((await post('/api/progress', { ...progress, page: 20 })).status, 400);
assert.equal((await post('/api/progress', { ...progress, chapterId: 'md:86ae1403-f1bf-4daa-bf0e-96a693ee110c' })).status, 400);
assert.equal((await (await get('/api/progress', alice)).json()).items[0].percent, 100);
assert.deepEqual((await (await get('/api/progress', bob)).json()).items, []);
const initialSettings = (await (await get('/api/settings', alice)).json()).settings; assert.equal(initialSettings.autoTranslate, true); assert.equal(initialSettings.targetLanguage, 'pt'); assert.equal(initialSettings.motion, true); assert.equal(initialSettings.economy, false);
assert.equal(initialSettings.autoReadSpeed, 24); assert.equal(initialSettings.autoRead, undefined);
assert.equal((await post('/api/settings', { settings: { autoTranslate: true, readerMode: 'paged', readerDirection: 'rtl', targetLanguage: 'pt', glossary: 'dragon = dragão', motion: false, economy: true } })).status, 200);
const settings = (await (await get('/api/settings', alice)).json()).settings; assert.equal(settings.readerDirection, 'rtl'); assert.equal(settings.autoTranslate, true); assert.equal(settings.glossary, 'dragon = dragão'); assert.equal(settings.motion, false); assert.equal(settings.economy, true);
assert.equal((await post('/api/settings', { settings: { motion: 'yes' } })).status, 400);
assert.equal((await post('/api/settings', { settings: { economy: 1 } })).status, 400);
assert.equal((await post('/api/settings', { settings: { autoReadSpeed: 40 } })).status, 200);
assert.equal((await (await get('/api/settings', alice)).json()).settings.autoReadSpeed, 40);
assert.equal((await post('/api/settings', { settings: { autoReadSpeed: 71 } })).status, 400);
assert.equal((await post('/api/settings', { settings: { autoRead: true } })).status, 400);
assert.equal((await post('/api/settings', { settings: { GEMINI_API_KEY: 'never-store-this' } })).status, 400);
const bobSettings = (await (await get('/api/settings', bob)).json()).settings; assert.equal(bobSettings.autoTranslate, true); assert.equal(bobSettings.motion, true); assert.equal(bobSettings.economy, false);
console.log('PASS: progress persists with string chapter IDs and validation; authenticated preference sync without secrets');

let profile = await (await get('/api/profiles/' + alice.user.id, bob)).json(); assert.equal(profile.private, true); assert.deepEqual(profile.library, []); assert.equal(profile.stats, null); assert.equal(profile.user.email, undefined); assert.equal(profile.user.bio, undefined);
await call(auth, request('/api/auth/privacy', { method: 'POST', cookie: alice.cookie, data: { visibility: 'public' } }), env);
profile = await (await get('/api/profiles/' + alice.user.id, bob)).json(); assert.equal(profile.private, false); assert.equal(profile.library.length, 1); assert.equal(profile.stats.completed, 1); assert.equal(profile.user.email, undefined); assert.equal(profile.progress, undefined);
console.log('PASS: private profiles hide bio/library/stats; public profiles never leak email or detailed reading progress');

const created = await post('/api/comments', { mediaId: item.id, chapterId: progress.chapterId, body: 'Gostei muito deste capítulo!', spoiler: true });
assert.equal(created.status, 201); const comment = (await created.json()).item; assert.equal(comment.user.id, alice.user.id); assert.equal(comment.user.email, undefined); assert.equal(comment.spoiler, true);
assert.equal((await post('/api/comments', { mediaId: item.id, body: '  GOSTEI muito deste capítulo!  ', spoiler: false })).status, 409);
assert.equal((await post('/api/comments/' + comment.id + '/like', { liked: true }, bob)).status, 200);
assert.equal((await post('/api/comments/' + comment.id + '/like', { liked: true }, bob)).status, 200);
let comments = await (await get('/api/comments?mediaId=local%3Adragon', bob)).json(); assert.equal(comments.items[0].likes, 1); assert.equal(comments.items[0].likedByMe, true); assert.equal(comments.items[0].mine, false);
assert.equal((await call(community, request('/api/comments/' + comment.id, { method: 'DELETE', cookie: bob.cookie }), env)).status, 403);
assert.equal((await post('/api/comments/' + comment.id + '/report', {}, bob)).status, 200);
assert.equal(DB.sqlite.prepare('SELECT COUNT(*) total FROM comment_reports').get().total, 1);
assert.equal((await call(community, request('/api/comments/' + comment.id, { method: 'DELETE', cookie: alice.cookie }), env)).status, 200);
comments = await (await get('/api/comments?mediaId=local%3Adragon')).json(); assert.deepEqual(comments.items, []); assert.equal(DB.sqlite.prepare('SELECT COUNT(*) total FROM comment_likes').get().total, 0); assert.equal(DB.sqlite.prepare('SELECT COUNT(*) total FROM comment_reports').get().total, 0);
assert.equal((await call(community, request('/api/comments', { method: 'POST', cookie: alice.cookie, origin: 'https://evil.test', data: { mediaId: item.id, body: 'Cross-site comment' } }), env)).status, 403);
console.log('PASS: comments persist, duplicates rejected, likes idempotent, reports saved, only authors delete, child rows cleaned');
const now = new Date().toISOString();
for (let index = 0; index < 498; index++) DB.sqlite.prepare('INSERT INTO manga_library VALUES(?,?,?,?,?)').run(alice.user.id, `local:book-${index}`, 'later', JSON.stringify({ id: `local:book-${index}`, title: 'Book', kind: 'novel', coverUrl: '' }), now);
const limits = await Promise.all(['limit-a', 'limit-b'].map(name => post('/api/library', { mediaId: 'local:' + name, kind: 'favorite', item: { ...item, id: 'local:' + name } })));
assert.deepEqual(limits.map(response => response.status).sort(), [200, 413]);
assert.equal(DB.sqlite.prepare('SELECT COUNT(*) total FROM manga_library WHERE user_id=?').get(alice.user.id).total, 500);
assert.equal((await post('/api/library', { mediaId: item.id, kind: 'reading' })).status, 200);
assert.equal(DB.sqlite.prepare('SELECT COUNT(*) total FROM manga_library WHERE user_id=?').get(alice.user.id).total, 500);
for (let index = 0; index < 198; index++) DB.sqlite.prepare('INSERT INTO reading_progress VALUES(?,?,?,?,?,?,?,?)').run(alice.user.id, `local:progress-${index}`, `local:progress-${index}:chapter-1`, 0, 1, 0, '{}', now);
await Promise.all(['progress-a', 'progress-b'].map(name => post('/api/progress', { ...progress, mediaId: 'local:' + name, chapterId: 'local:' + name + ':chapter-1', item: { ...item, id: 'local:' + name } })));
assert.equal(DB.sqlite.prepare('SELECT COUNT(*) total FROM reading_progress WHERE user_id=?').get(alice.user.id).total, 200);
console.log('PASS: concurrent library writes respect 500-row cap, status switches work at capacity, progress retains exactly latest 200');
DB.sqlite.close();
console.log('All community and library tests passed with actual SQLite accounts.');
