import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../web/translation/lib/providers.js',import.meta.url),'utf8');
function providerWith(requestJSON){const context={SD:{requestJSON,targetLanguage:()=> 'pt',checkCancelled(){}},SDOCR:{cleanText:text=>String(text||''),overlapRatio:()=>1},Date,Map,Set};vm.createContext(context);vm.runInContext(source,context);return context.SDProviders;}
const result=(texts,provider)=>({ok:true,provider,translations:texts.map(text=>({text:'Traduzido '+text,sourceLanguage:'en'}))});
const calls=[];const limited=Object.assign(new Error('IA em espera'),{status:429,code:'GEMINI_RATE_LIMIT',provider:'gemini',retryable:true,retryAfter:60});
const fallback=providerWith(async(path,body)=>{calls.push(body.provider);if(body.provider==='gemini')throw limited;return result(body.texts,'google');});
const first=await fallback.translate(['Hello'],{engine:'gemini',sourceLanguage:'auto'});assert.deepEqual(calls,['gemini','google']);assert.equal(first.usedProvider,'google');assert.equal(first.provider,'google');assert.ok(first.warnings.length);
const second=await fallback.translate(['Other page'],{engine:'gemini'});assert.deepEqual(calls,['gemini','google','google']);assert.equal(second.usedProvider,'google');await assert.rejects(()=>fallback.vision('data:image/png;base64,AAAA',100,100,{engine:'gemini'}),error=>error===limited);
let abortCalls=0;const abort=providerWith(async()=>{abortCalls++;throw Object.assign(new Error('Cancelado'),{name:'AbortError',status:429});});await assert.rejects(()=>abort.translate(['Cancelled'],{engine:'gemini'}),error=>error.name==='AbortError');assert.equal(abortCalls,1);
let requestLimitCalls=0;const requestLimited=providerWith(async()=>{requestLimitCalls++;throw Object.assign(new Error('Limite comum'),{status:429,code:'TRANSLATION_REQUEST_LIMIT',provider:'request',retryable:true,retryAfter:30});});await assert.rejects(()=>requestLimited.translate(['Shared limiter'],{engine:'gemini'}),/Limite comum/);assert.equal(requestLimitCalls,1);
const sequence=[],texts=Array.from({length:25},(_,index)=>'text-'+index);let fail=true;
const resumed=providerWith(async(path,body)=>{sequence.push({provider:body.provider,first:body.texts[0]});if(body.texts[0]==='text-12'&&fail){if(body.provider==='gemini')throw limited;fail=false;throw Object.assign(new Error('Básico em espera'),{status:429,code:'GOOGLE_RATE_LIMIT',provider:'google',retryable:true,retryAfter:2});}return result(body.texts,body.provider);});
await assert.rejects(()=>resumed.translate(texts,{engine:'gemini'}),/Básico em espera/);const recovered=await resumed.translate(texts,{engine:'gemini'});assert.equal(recovered.translations.length,25);assert.equal(sequence.filter(call=>call.first==='text-0').length,1,'Successful batches must be reused after a later quota failure.');assert.equal(recovered.usedProvider,'mixed');assert.equal(recovered.provider,'google');assert.ok(recovered.warnings.length);assert.deepEqual([...recovered.providers],['gemini','google']);
for(const [code,status]of [['GEMINI_NOT_CONFIGURED',503],['AUTH_REQUIRED',401],['DAILY_USER_QUOTA',429]]){const attempts=[];const service=providerWith(async(path,body)=>{attempts.push(body.provider);if(body.provider==='gemini')throw Object.assign(new Error(code),{code,status,provider:'gemini',retryable:false});return result(body.texts,body.provider);});const translated=await service.translate(['Test'],{engine:'gemini'});assert.equal(translated.usedProvider,'google');assert.deepEqual(attempts,['gemini','google']);}
const cloudflare=providerWith(async(path,body)=>result(body.texts,'cloudflare'));const cf=await cloudflare.translate(['Workers AI'],{engine:'local'});assert.equal(cf.provider,'cloudflare');assert.equal(cf.usedProvider,'cloudflare');assert.equal(cf.requestProvider,'google');
console.log('PASS: Gemini rate/auth/config/quota fallback, real used-provider metadata, provider cooldown reuse, AbortError/shared-limit exclusion and partial-batch recovery without duplicate requests. Transport responses simulated.');
