import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const sandbox={Intl,console,setTimeout,clearTimeout,Uint8Array,Uint8ClampedArray,Map,Set,SD:{targetLanguage:()=> 'pt',assetURL:path=>`https://mahuwa.test/translation/${path}`,checkCancelled:()=>{}},location:{origin:'https://mahuwa.test'}};vm.createContext(sandbox);
for(const nameof of ['ocr','render','providers'])vm.runInContext(await readFile(new URL(`../web/translation/lib/${nameof}.js`,import.meta.url),'utf8'),sandbox);
const {SDOCR:ocr,SDRender:render,SDProviders:providers}=sandbox;const plain=value=>JSON.parse(JSON.stringify(value));
const tiles=ocr.planTiles(720,5800);assert.equal(tiles[0].y,0);assert.equal(tiles.at(-1).y+tiles.at(-1).h,5800);for(let index=1;index<tiles.length;index++)assert.equal(tiles[index-1].y+tiles[index-1].h-tiles[index].y,180);
assert.deepEqual(plain(ocr.languagePacks({sourceLanguage:'ja-vert'})),['jpn_vert','eng']);assert.throws(()=>ocr.languagePacks({sourceLanguage:'hi'}),/IA/);
const line=(text,x,y,w,h=28,punctuationOnly=false)=>({text,confidence:90,punctuationOnly,box:{x,y,w,h},cleanupBoxes:[{x,y,w,h}]});
const blocks=ocr.mergeLines([line('HELLO, MY FR',237,204,284),line('IEND',534,204,88),line('!',623,204,10,28,true),line('THE DRAGON IS HERE',237,260,415),line('.',653,280,5,8,true),line('SECOND BALLOON',280,724,330),line('SECOND LINE',280,780,330)],null);
assert.equal(blocks.length,2);assert.equal(blocks[0].text,'HELLO, MY FRIEND!\nTHE DRAGON IS HERE.');assert.equal(blocks[0].cleanupBoxes.length,5);
const vertical=ocr.mergeVerticalLines([line('左の列',40,30,20,160),line('右の列',70,30,20,160)],null);assert.equal(vertical.length,1);assert.equal(vertical[0].text,'右の列\n左の列');assert.equal(vertical[0].cleanupBoxes.length,2);
assert.equal(ocr.deduplicate([{text:'HELLO',confidence:90,box:{x:10,y:10,w:100,h:20}},{text:'HELLO',confidence:80,box:{x:11,y:11,w:100,h:20}},{text:'HELLO',confidence:95,box:{x:10,y:300,w:100,h:20}}]).length,2);
console.log('PASS: browser-port tiling, installed language packs, duplicate suppression, split-word/punctuation balloon merge');
class Raster{
  constructor(w,h,color=[255,255,255]){this.canvas={width:w,height:h};this.pixels=new Uint8ClampedArray(w*h*4);this.paint(0,0,w,h,color);}
  paint(x,y,w,h,color){for(let row=Math.max(0,y);row<Math.min(this.canvas.height,y+h);row++)for(let col=Math.max(0,x);col<Math.min(this.canvas.width,x+w);col++)this.pixels.set([...color,255],(row*this.canvas.width+col)*4);}
  fillRect(x,y,w,h){this.paint(x,y,w,h,this.fillStyle.match(/[\d.]+/g).map(Number));}
  createImageData(w,h){return{width:w,height:h,data:new Uint8ClampedArray(w*h*4)};}
  getImageData(x,y,w,h){const image=this.createImageData(w,h);for(let row=0;row<h;row++)for(let col=0;col<w;col++){const index=((y+row)*this.canvas.width+x+col)*4;image.data.set(this.pixels.subarray(index,index+4),(row*w+col)*4);}return image;}
  putImageData(image,x,y){for(let row=0;row<image.height;row++)for(let col=0;col<image.width;col++){const index=((y+row)*this.canvas.width+x+col)*4;this.pixels.set(image.data.subarray((row*image.width+col)*4,(row*image.width+col)*4+4),index);}}
  pixel(x,y){return [...this.pixels.subarray((y*this.canvas.width+x)*4,(y*this.canvas.width+x)*4+3)];}
}
const image=new Raster(100,70);image.paint(35,28,12,12,[0,0,0]);image.paint(54,28,2,8,[0,0,0]);image.paint(54,39,2,2,[0,0,0]);image.paint(58,0,2,70,[0,0,0]);render.cleanupRectangle(image,{x:34,y:27,w:17,h:14},{cleanup:'smart'});assert.deepEqual(image.pixel(40,32),[255,255,255]);assert.deepEqual(image.pixel(54,31),[255,255,255]);assert.deepEqual(image.pixel(54,40),[255,255,255]);assert.deepEqual(image.pixel(58,31),[0,0,0]);
const colored=new Raster(100,70,[238,210,176]);colored.paint(35,28,12,10,[0,0,0]);render.cleanupRectangle(colored,{x:35,y:28,w:12,h:10},{cleanup:'smart'});assert.deepEqual(colored.pixel(40,32),[238,210,176]);
const artwork=new Raster(100,70);for(let y=0;y<70;y++)for(let x=0;x<100;x++)artwork.paint(x,y,1,1,[(x*17+y*3)%256,(x*5+y*11)%256,(x*13+y*7)%256]);artwork.paint(20,15,55,40,[255,255,255]);artwork.paint(35,28,12,10,[0,0,0]);const originalPixels=artwork.pixels.slice();render.cleanupRectangle(artwork,{x:35,y:28,w:12,h:10},{cleanup:'smart'});for(let y=0;y<70;y++)for(let x=0;x<100;x++)if(x<20||x>=75||y<15||y>=55){const offset=(y*100+x)*4;assert.deepEqual(artwork.pixels.subarray(offset,offset+4),originalPixels.subarray(offset,offset+4));}
let dimensions=[100,70],created=[];sandbox.Image=class{constructor(){[this.naturalWidth,this.naturalHeight]=dimensions;}set src(value){this.pixels=originalPixels;queueMicrotask(()=>this.onload());}};
sandbox.document={createElement(tag){assert.equal(tag,'canvas');const target={width:0,height:0,getContext(){if(!this.raster){this.raster=new Raster(this.width,this.height);this.raster.canvas=this;this.raster.drawImage=(source,...args)=>{assert.deepEqual(args,[0,0]);this.raster.pixels.set(source.pixels||source.raster.pixels);};}return this.raster;},toDataURL(type){assert.equal(type,'image/png');return'data:image/png;base64,AAAA';}};created.push(target);return target;}};
const native=await render.load('data:image/png;base64,AAAA');assert.equal(native.scale,1);assert.equal(native.canvas.width,100);assert.equal(native.canvas.height,70);assert.deepEqual(native.canvas.raster.pixels,originalPixels);const unchanged=await render.render(native.canvas,[],{targetLanguage:'pt'});assert.equal(unchanged.width,100);assert.equal(unchanged.height,70);assert.deepEqual(created.at(-1).raster.pixels,originalPixels);assert.ok(unchanged.dataUrl.startsWith('data:image/png;'));dimensions=[6000,5000];await assert.rejects(()=>render.load('data:image/png;base64,AAAA'),/24 milhões/);
console.log('PASS: native image dimensions, no resampling, lossless PNG export path, unchanged character/artwork pixel arrays outside cleanup and oversized-page explicit error');
const divider=new Raster(200,150);divider.paint(0,64,200,3,[0,0,0]);assert.equal(ocr.mergeLines([line('UPPER',30,30,100,20),line('LOWER',30,80,100,20)],divider).length,2);
const dark=new Raster(200,150,[0,0,0]);assert.equal(ocr.mergeLines([line('WHITE',30,30,100,20),line('TYPE',30,80,100,20)],dark).length,1);
const moved=render.sanitizeBlocks([{translated:'Moved',text:'Source',box:{x:150,y:60,w:50,h:20},cleanupBoxes:[{x:30,y:10,w:50,h:20}]}],300,200);assert.deepEqual(plain(moved[0].cleanupBoxes[0]),{x:30,y:10,w:50,h:20});
console.log('PASS: original glyph/punctuation pixels removed, nearby border and coloured background retained, dark balloons merge, manual destination moves keep original cleanup mask');
const requests=[];sandbox.SD.requestJSON=async(path,body)=>{requests.push({path,body});if(path.includes('vision'))return{ok:true,blocks:[{text:'こんにちは',translated:'Olá',sourceLanguage:'ja',confidence:95,box:[100,200,300,600],lineBoxes:[[100,200,300,600]]}],sourceLanguage:'ja'};return{ok:true,translations:body.texts.map(text=>({text:`trad:${text}`,sourceLanguage:'en'}))};};
const vision=await providers.vision('data:image/png;base64,AAAA',1000,2000,{targetLanguage:'pt',minConfidence:40});assert.deepEqual(plain(vision.blocks[0].box),{x:200,y:200,w:400,h:400});assert.equal(requests[0].path,'/api/translate/vision');assert.ok(!JSON.stringify(requests[0]).includes('geminiKey'));
const textResult=await providers.translate(Array(25).fill('Hello'),{engine:'local',targetLanguage:'pt',sourceLanguage:'auto'});assert.equal(textResult.translations.length,25);assert.equal(requests.slice(1).length,3);assert.ok(requests.slice(1).every(request=>request.path==='/api/translate/text'&&request.body.texts.length<=12));
let called=false;await assert.rejects(()=>providers.translate(['x'],{engine:'local'},()=>{},null,()=>{called=true;throw new Error('cancelado');}),/cancelado/);assert.equal(called,true);
for(const file of ['../web/js/translation-bridge.js','../web/js/translator.js','../web/translation/lib/ocr.js','../web/translation/lib/providers.js'])assert.ok(!(await readFile(new URL(file,import.meta.url),'utf8')).includes('chrome.'));
console.log('PASS: fixed same-origin browser bridge, Gemini normalized coordinates, bounded text batches, cancellation and no extension API dependency');
