const escapeHTML=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const idPattern=/^[a-zA-Z0-9]{1,80}$/;
const memoryCache=new Map();
const CACHE_KEY='mh_giphy_ids_v1',ID_TTL=6*60*60*1000,LIST_TTL=2*60*1000;

export function giphyId(value){return /^giphy:([a-zA-Z0-9]{1,80})(?:\?x=\d+(?:\.\d+)?&y=\d+(?:\.\d+)?&zoom=\d+(?:\.\d+)?)?$/.exec(value||'')?.[1]||null;}
export function giphyMedia(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(u.hostname==='giphy.com'||u.hostname.endsWith('.giphy.com'))?u.href:null}catch{return null}}
export function giphyAnalyticsUrl(gif,event){try{const raw=gif?.analytics?.[event]?.url,u=new URL(raw);return u.protocol==='https:'&&u.hostname==='giphy-analytics.giphy.com'&&!u.username&&!u.password?u.href:null}catch{return null}}
export function trackGiphy(gif,event,fetcher=globalThis.fetch){const url=giphyAnalyticsUrl(gif,event);if(!url)return;try{void fetcher(url,{method:'GET',mode:'no-cors',credentials:'omit',cache:'no-store',keepalive:true,referrerPolicy:'no-referrer'}).catch(()=>{})}catch{}}

function storageRead(){try{return JSON.parse(sessionStorage.getItem(CACHE_KEY)||'{}')}catch{return {}}}
function storageWrite(id,data){try{const all=storageRead(),now=Date.now();all[id]={until:now+ID_TTL,data};for(const [key,value] of Object.entries(all))if(!value?.until||value.until<now)delete all[key];const keys=Object.keys(all);for(const key of keys.slice(0,Math.max(0,keys.length-50)))delete all[key];sessionStorage.setItem(CACHE_KEY,JSON.stringify(all))}catch{}}
function cachedId(id){try{const item=storageRead()[id];return item?.until>Date.now()?item.data:null}catch{return null}}

export function giphyRequest(_key,{query='manga anime',trending=false,offset=0,id}={}){
 if(id&&!idPattern.test(id))throw new Error('GIF inválido.');
 if(id)return `/api/giphy/gifs/${encodeURIComponent(id)}`;
 const url=new URL(trending?'/api/giphy/trending':'/api/giphy/search','https://mahuwa.local');
 url.searchParams.set('offset',String(Math.max(0,Math.min(trending?499:4999,offset))));
 if(!trending)url.searchParams.set('q',String(query).slice(0,50));
 return url.pathname+url.search;
}
export function createGiphyClient({fetcher=globalThis.fetch}={}){
 let configTask=null;
 async function config(){if(!configTask)configTask=fetcher('/api/giphy/config',{credentials:'same-origin',cache:'no-store'}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Não foi possível conectar a galeria.');if(!data.configured)throw new Error('A chave GIPHY_API_KEY não está disponível neste deploy do Cloudflare.');return data}).catch(e=>{configTask=null;throw e});return configTask}
 async function read(options={},signal){
   const cacheKey=options.id?`id:${options.id}`:`${options.trending?'trending':'search'}:${options.query||''}:${options.offset||0}`;
   const ttl=options.id?ID_TTL:LIST_TTL,cached=memoryCache.get(cacheKey);if(cached?.until>Date.now())return cached.data;
   if(options.id){const stored=cachedId(options.id);if(stored){memoryCache.set(cacheKey,{until:Date.now()+ID_TTL,data:stored});return stored}}
   await config();
   const response=await fetcher(giphyRequest(null,options),{signal,credentials:'same-origin',cache:'no-store'});
   const data=await response.json().catch(()=>({}));
   if(!response.ok)throw new Error(data.error||(response.status===429?'A galeria atingiu o limite de consultas. Aguarde um pouco.':'O GIPHY não respondeu agora. Tente novamente em instantes.'));
   memoryCache.set(cacheKey,{until:Date.now()+ttl,data});if(options.id)storageWrite(options.id,data);return data;
 }
 return {read};
}
const powered=()=>'<a class="giphy-attribution" href="https://giphy.com/" target="_blank" rel="noopener noreferrer"><img src="/assets/powered-by-giphy-text.png?v=1.2.0" width="200" height="22" alt="Powered By GIPHY"></a>';
export function giphyPage(){return `<div class="page-wrap"><section class="giphy-page"><div class="giphy-heading"><div><span class="eyebrow">SEU PERFIL EM MOVIMENTO</span><h1>Escolha um GIF para seu universo.</h1><p>Pesquise personagens, reações e animações. O Mahuwa Dragon salva apenas o ID do GIF e seu enquadramento.</p></div></div><form class="giphy-search" role="search"><label class="sr-only" for="gif-query">Pesquisar GIFs</label><input id="gif-query" name="query" maxlength="50" value="manga anime" placeholder="Pesquise um anime, personagem ou reação" autocomplete="off"><button class="primary" type="submit">Pesquisar</button></form><div class="giphy-chips" role="group" aria-label="Explorar GIFs"><button data-gif-query="manga anime" class="selected">Anime & mangá</button><button data-gif-query="One Piece">One Piece</button><button data-gif-query="Dragon Ball">Dragon Ball</button><button data-gif-query="Jujutsu Kaisen">Jujutsu Kaisen</button><button data-gif-query="manhwa">Manhwa</button><button data-gif-trending>Em alta no GIPHY</button></div><div class="giphy-toolbar"><span id="gif-results-label">Escolha seu universo.</span><div class="giphy-toolbar-actions">${powered()}<button class="secondary" type="button" data-gif-motion aria-pressed="true">Pausar animações</button></div></div><p class="giphy-status" role="status" aria-live="polite"></p><div class="giphy-grid"></div><button class="secondary giphy-more" type="button" hidden>Carregar mais GIFs</button><dialog class="giphy-dialog"><button class="icon-btn giphy-close" aria-label="Fechar prévia">×</button><div class="giphy-preview"></div><div class="giphy-selection"></div></dialog></section></div>`;}

export function mountGiphy(host,{client=createGiphyClient(),user,onLogin,onSelect,onError}={}){
 const abort=new AbortController(),signal=abort.signal,grid=host.querySelector('.giphy-grid'),form=host.querySelector('form'),input=host.querySelector('#gif-query'),status=host.querySelector('.giphy-status'),more=host.querySelector('.giphy-more'),dialog=host.querySelector('dialog');
 let dead=false,generation=0,requestAbort=null,rows=[],offset=0,total=0,busy=false,selected=null,motion=!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches,trending=false,query='manga anime',downloadAbort=null;
 const e=escapeHTML,seen=new Set();
 function showStatus(text,error=false){status.textContent=text;status.classList.toggle('form-error',error)}
 const still=gif=>giphyMedia(gif.images?.fixed_width_still?.url||gif.images?.original_still?.url),preview=gif=>giphyMedia(gif.images?.fixed_width?.url||gif.images?.fixed_height?.url||gif.images?.original?.url),movie=gif=>giphyMedia(gif.images?.fixed_width?.mp4||gif.images?.fixed_height?.mp4);
 function media(gif,large=false){const poster=still(gif),mp4=movie(gif),url=large?giphyMedia(gif.images?.downsized?.url||gif.images?.original?.url):preview(gif);if(mp4&&!large)return `<video data-gif-id="${e(gif.id)}" muted loop playsinline preload="none" ${poster?`poster="${e(poster)}"`:''} aria-label="${e(gif.title||'GIF animado')}" data-src="${e(mp4)}"></video>`;return `<img data-gif-id="${e(gif.id)}" src="${e(motion?url:poster||url)}" alt="${e(gif.title||'GIF')}" loading="lazy" decoding="async" data-animated="${e(url)}" data-still="${e(poster||url)}">`}
 const observer=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{for(const {target,isIntersecting} of entries){const gif=rows.find(row=>row.id===target.dataset.gifId);if(isIntersecting&&gif&&!seen.has(gif.id)){seen.add(gif.id);trackGiphy(gif,'onload')}if(target.tagName==='VIDEO'){target.dataset.visible=String(isIntersecting);if(isIntersecting&&motion&&!host.ownerDocument.hidden){if(!target.src)target.src=target.dataset.src;target.play().catch(()=>{})}else target.pause()}}},{rootMargin:'150px'}):null;
 function activate(){grid.querySelectorAll('[data-gif-id]:not([data-observed])').forEach(node=>{node.dataset.observed='true';if(observer)observer.observe(node);else{const gif=rows.find(row=>row.id===node.dataset.gifId);if(gif&&!seen.has(gif.id)){seen.add(gif.id);trackGiphy(gif,'onload')}if(node.tagName==='VIDEO'&&motion){node.src=node.dataset.src;node.play().catch(()=>{})}}})}
 function updateMotion(){const button=host.querySelector('[data-gif-motion]');button.textContent=motion?'Pausar animações':'Animar GIFs';button.setAttribute('aria-pressed',String(motion));host.querySelectorAll('video').forEach(v=>{if(motion&&!host.ownerDocument.hidden&&(!observer||v.dataset.visible==='true')){if(!v.src)v.src=v.dataset.src;v.play().catch(()=>{})}else v.pause()});host.querySelectorAll('img[data-animated]').forEach(img=>{img.src=motion?img.dataset.animated:img.dataset.still})}
 async function load(reset=false){if(dead||busy&&!reset)return;if(reset){requestAbort?.abort();offset=0;rows=[];seen.clear();grid.replaceChildren();observer?.disconnect()}const token=++generation;requestAbort=new AbortController();busy=true;more.disabled=true;showStatus(reset?'Buscando seu próximo avatar…':'Carregando mais GIFs…');try{const data=await client.read({query,trending,offset},requestAbort.signal);if(dead||token!==generation)return;const next=Array.isArray(data.data)?data.data.filter(g=>idPattern.test(g?.id||'')):[];rows.push(...next);offset+=Number(data.pagination?.count??next.length);total=Number(data.pagination?.total_count??offset);grid.insertAdjacentHTML('beforeend',next.map(gif=>`<button type="button" class="giphy-card" data-gif-select="${e(gif.id)}" aria-label="Ver ${e(gif.title||'GIF')}">${media(gif)}<span>Escolher ↗</span></button>`).join(''));activate();more.textContent='Carregar mais GIFs';host.querySelector('#gif-results-label').textContent=trending?'Em alta no GIPHY':`GIFs para “${query}”`;showStatus(next.length?'':'Nenhum GIF encontrado. Experimente outro nome.');more.hidden=!next.length||offset>=total||offset>(trending?499:4999)}catch(error){if(dead||token!==generation||error.name==='AbortError')return;showStatus(error.message,true);more.hidden=false;more.textContent='Tentar novamente'}finally{if(!dead&&token===generation){busy=false;more.disabled=false;form.querySelector('button').disabled=false}}}
 function open(gif){selected=gif;trackGiphy(gif,'onclick');host.querySelector('.giphy-preview').innerHTML=media(gif,true);const owner=gif.user?.display_name||gif.username;host.querySelector('.giphy-selection').innerHTML=`<div class="giphy-selection-heading"><h2>${e(gif.title||'Seu novo GIF')}</h2>${powered()}</div>${owner?`<p>Por ${e(owner)}</p>`:''}<div class="giphy-actions"><button class="primary" data-use-gif>Usar no meu perfil</button><button class="secondary" data-download-gif>Baixar GIF</button><button class="secondary" data-download-still>Baixar imagem</button></div><p class="giphy-action-status" role="status"></p>`;dialog.showModal();updateMotion()}
 async function download(photo){const gif=selected,url=photo?giphyMedia(gif?.images?.original_still?.url):giphyMedia(gif?.images?.original?.url),message=dialog.querySelector('.giphy-action-status');if(!url){message.textContent='Este arquivo não está disponível para baixar.';return}downloadAbort?.abort();downloadAbort=new AbortController();message.textContent='Preparando download…';try{const response=await fetch(url,{signal:downloadAbort.signal,credentials:'omit',cache:'no-store'});if(!response.ok)throw new Error();const blob=await response.blob();if(dead||!dialog.open||selected!==gif)return;const objectURL=URL.createObjectURL(blob),a=document.createElement('a');a.href=objectURL;a.download=`MahuwaDragon-${gif.id}.${photo?({'image/png':'png','image/jpeg':'jpg','image/gif':'gif','image/webp':'webp'}[blob.type.split(';')[0]]||'gif'):'gif'}`;a.click();setTimeout(()=>URL.revokeObjectURL(objectURL),1000);message.textContent='Download pronto.'}catch(error){if(error.name!=='AbortError')message.textContent='Não foi possível baixar agora.'}}
 host.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||!host.contains(button))return;if(button.matches('[data-gif-query],[data-gif-trending]')){trending=button.hasAttribute('data-gif-trending');query=button.dataset.gifQuery||'manga anime';input.value=trending?'':query;host.querySelectorAll('.giphy-chips button').forEach(b=>b.classList.toggle('selected',b===button));void load(true)}else if(button.hasAttribute('data-gif-select')){const gif=rows.find(g=>g.id===button.dataset.gifSelect);if(gif)open(gif)}else if(button.hasAttribute('data-gif-motion')){motion=!motion;updateMotion()}else if(button.classList.contains('giphy-more'))void load();else if(button.classList.contains('giphy-close'))dialog.close();else if(button.hasAttribute('data-download-gif'))void download(false);else if(button.hasAttribute('data-download-still'))void download(true);else if(button.hasAttribute('data-use-gif')){if(!user?.()){dialog.close();onLogin?.();return}const gif=selected,message=dialog.querySelector('.giphy-action-status');button.disabled=true;try{await onSelect?.(gif.id);trackGiphy(gif,'onsent');if(dead)return;dialog.close()}catch(error){message.textContent=error.message;onError?.(error)}finally{if(!dead)button.disabled=false}}},{signal});
 form.addEventListener('submit',event=>{event.preventDefault();if(!input.value.trim())return;query=input.value.trim();trending=false;host.querySelectorAll('.giphy-chips button').forEach(b=>b.classList.toggle('selected',b.dataset.gifQuery===query));void load(true)},{signal});
 dialog.addEventListener('close',()=>{downloadAbort?.abort();host.querySelector('.giphy-preview').replaceChildren();selected=null},{signal});host.ownerDocument.addEventListener('visibilitychange',updateMotion,{signal});updateMotion();void load(true);
 return {destroy(){dead=true;++generation;abort.abort();requestAbort?.abort();downloadAbort?.abort();observer?.disconnect();host.querySelectorAll('video').forEach(video=>{video.pause?.();video.removeAttribute('src');video.load?.()});if(dialog.open)dialog.close()}};
}

export function observeGiphyAvatars(root,{client=createGiphyClient()}={}){
 let dead=false,scheduled=false;const inFlight=new Map(),controllers=new Set();
 async function scan(){scheduled=false;if(dead)return;const groups=new Map();root.querySelectorAll('img[data-giphy-avatar]:not([data-giphy-resolving])').forEach(img=>{const id=img.dataset.giphyAvatar;if(!idPattern.test(id))return;img.dataset.giphyResolving='true';if(!groups.has(id))groups.set(id,[]);groups.get(id).push(img)});for(const [id,images] of groups){if(dead)return;let task=inFlight.get(id);if(!task){const abort=new AbortController();controllers.add(abort);task=client.read({id},abort.signal).finally(()=>{controllers.delete(abort);inFlight.delete(id)});inFlight.set(id,task)}try{const data=await task,gif=data.data,src=giphyMedia(gif?.images?.fixed_height?.url||gif?.images?.original?.url);if(dead)return;if(!src)continue;trackGiphy(gif,'onload');for(const img of images)if(img.isConnected&&img.dataset.giphyAvatar===id){img.src=src;img.title='GIF via GIPHY';img.removeAttribute('data-giphy-resolving')}}catch{for(const img of images)img.removeAttribute('data-giphy-resolving')}}}
 function queue(){if(!scheduled&&!dead){scheduled=true;queueMicrotask(scan)}}const observer=new MutationObserver(queue);observer.observe(root,{childList:true,subtree:true});queue();return {refresh:queue,destroy(){dead=true;observer.disconnect();for(const c of controllers)c.abort();inFlight.clear()}};
}
