import {translateImage,renderImage,translateTexts,clearTranslationCache,defaults} from './translator.js';

const PREFERENCE_KEY='mahuwa.reader.preferences';
const INITIAL={readerMode:'webtoon',readerDirection:'ltr',readerZoom:100,readerWidth:1200,readerFontSize:19,autoReadSpeed:24,...defaults};
const LANGUAGE_OPTIONS=[['auto','Detectar automaticamente'],['en','Inglês'],['ja','Japonês'],['ja-vert','Japonês vertical'],['ko','Coreano'],['zh-CN','Chinês simplificado'],['zh-TW','Chinês tradicional'],['pt','Português'],['es','Espanhol'],['fr','Francês'],['de','Alemão'],['it','Italiano'],['ru','Russo'],['ar','Árabe']];
function node(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=text;return element;}
function button(label,title,handler,className='md-reader-button'){const element=node('button',className,label);element.type='button';element.title=title||label;element.addEventListener('click',handler);return element;}
function select(options,value,handler,title){const element=node('select','md-reader-select');element.setAttribute('aria-label',title);for(const [id,label]of options){const option=node('option','',label);option.value=id;element.append(option);}element.value=value;element.addEventListener('change',()=>handler(element.value));return element;}
export function splitNovelText(text,maxLength=3000){
  const result=[];for(const paragraph of String(text||'').replace(/\r/g,'').split(/\n\s*\n/)){
    let remaining=paragraph.trim();while(remaining.length>maxLength){const prefix=remaining.slice(0,maxLength),boundary=Math.max(prefix.lastIndexOf('. '),prefix.lastIndexOf(' '),prefix.lastIndexOf('\n'));const cut=boundary>maxLength*.55?boundary+1:maxLength;result.push(remaining.slice(0,cut).trim());remaining=remaining.slice(cut).trimStart();}if(remaining)result.push(remaining);
  }return result;
}
export function nonPortuguese(language){return !/^pt(?:-|$)/i.test(String(language||'auto'));}
export function translationRecoveryPolicy(error,now=Date.now()){
  const code=String(error?.code||''),daily=/DAILY_.*QUOTA|QUOTA_EXCEEDED|GEMINI_DAILY_LIMIT/.test(code),rate=/RATE_LIMIT/.test(code)||Number(error?.status)===429;
  const retryable=error?.retryable===true||(error?.retryable===undefined&&rate&&!daily);
  if(error?.name==='AbortError'||!daily&&!rate&&!retryable)return null;
  const raw=typeof error.resetAt==='number'?error.resetAt:Date.parse(error.resetAt||''),reset=raw>0&&raw<100000000000?raw*1000:raw;
  const seconds=Number(error.retryAfter),fallback=daily?Date.UTC(new Date(now).getUTCFullYear(),new Date(now).getUTCMonth(),new Date(now).getUTCDate()+1):now+30000;
  const validReset=Number.isFinite(reset)&&reset>now,bySeconds=Number.isFinite(seconds)&&seconds>=0?now+Math.max(1,seconds)*1000:validReset?now+1000:fallback;
  const until=Math.max(now+1000,validReset?reset:0,bySeconds);
  return {code,daily,until,retryable,recover:retryable&&until-now<=120000,message:String(error.message||'O serviço de tradução está aguardando liberação.')};
}
export function createTranslationCooldown({now=Date.now,schedule=setTimeout,cancel=clearTimeout,onChange=()=>{},onRetry=()=>{}}={}){
  let state=null,timer=null,destroyed=false;const recovered=new Set();
  function snapshot(){return state?{...state,remaining:Math.max(0,state.until-now())}:null;}
  function tick(){timer=null;if(destroyed||!state)return;const remaining=Math.max(0,state.until-now());onChange(snapshot());if(remaining>0){timer=schedule(tick,Math.min(remaining,remaining>120000?60000:1000));return;}if(state.recover){const record=state.record;state=null;onChange(null);onRetry(record);}}
  return {
    pause(error,record,allowRecovery=true){const policy=translationRecoveryPolicy(error,now());if(!policy)return false;cancel(timer);state={...policy,record,recover:policy.recover&&allowRecovery&&!recovered.has(record)};if(state.recover)recovered.add(record);tick();return true;},
    blocked(manual=false){return !!state&&(state.until>now()||!manual);},
    manual(){if(state?.until>now())return false;if(!state)return true;cancel(timer);state=null;onChange(null);return true;},
    cancelRecovery(){if(state)state.recover=false;},
    get state(){return snapshot();},
    destroy(){destroyed=true;cancel(timer);state=null;}
  };
}
function readPreferences(){try{return {...INITIAL,...JSON.parse(localStorage.getItem(PREFERENCE_KEY)||'{}')};}catch{return {...INITIAL};}}
function blobDataURL(blob,signal){return new Promise((resolve,reject)=>{const reader=new FileReader();const cleanup=()=>signal?.removeEventListener('abort',abort);const abort=()=>{reader.abort();cleanup();reject(new DOMException('Leitura cancelada.','AbortError'));};reader.onload=()=>{cleanup();resolve(reader.result);};reader.onerror=()=>{cleanup();reject(new Error('Não foi possível abrir esta imagem.'));};if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});reader.readAsDataURL(blob);});}

export function chapterPercent({mode,page,total,top,height,view,completed=false}){const max=Math.max(0,(Number(height)||0)-(Number(view)||0)),fraction=max?Math.max(0,Math.min(1,(Number(top)||0)/max)):0;return completed?100:Math.max(0,Math.min(100,mode==='paged'?((page+fraction)/Math.max(1,total))*100:fraction*100));}
export function createAutoScroller({viewport,speed,hold,onEnd,onFrame,request=callback=>requestAnimationFrame(callback),cancel=id=>cancelAnimationFrame(id)}){
  let running=false,id=null,last=null;
  function tick(time){if(!running)return;const delta=last===null?0:Math.max(0,Math.min(64,time-last));last=time;const max=Math.max(0,viewport.scrollHeight-viewport.clientHeight);if(!hold()){if(viewport.scrollTop>=max-1){running=false;id=null;last=null;onEnd?.();return;}viewport.scrollTop=Math.min(max,viewport.scrollTop+Math.max(8,Math.min(70,Number(speed())||24))*delta/1000);onFrame?.();}id=request(tick);}
  return{start(){if(running)return;running=true;last=null;id=request(tick);},stop(){running=false;last=null;if(id!==null)cancel(id);id=null;},get running(){return running;}};
}

export function mountReader(container,options){
  if(!document.querySelector('link[data-mahuwa-reader]')){const link=node('link');link.rel='stylesheet';link.href='/css/reader.css';link.dataset.mahuwaReader='true';document.head.append(link);}
  const {media,chapter,pages=[],previousId,nextId,onNavigate,onProgress,onClose,api}=options;
  const translatePage=options.translation?.image||translateImage,translateCopy=options.translation?.text||translateTexts;
  const lifetime=new AbortController(),root=node('section','md-reader'),toolbar=node('header','md-reader-topbar'),viewport=node('div','md-reader-viewport'),content=node('div','md-reader-content'),footer=node('footer','md-reader-footer');
  root.setAttribute('aria-label',`Leitor — ${media.title}`);root.tabIndex=-1;viewport.tabIndex=0;viewport.setAttribute('aria-label','Páginas do capítulo');viewport.append(content);
  const preferences=readPreferences();let destroyed=false,booted=false,current=Math.max(0,Math.min(pages.length-1,Number(chapter.startPage||options.initialPage||1)-1)),busy=Promise.resolve(),showOriginal=false,compare=false,geminiAvailable=false,activeJob=null,saveTimer,progressTimer,editor=null,reviewing=false,completed=false,lastProgressSave=0;
  const title=node('div','md-reader-title');title.append(node('strong','',media.title),node('span','',chapter.title||`Capítulo ${chapter.number??'—'}`));
  if(String(media.id).startsWith('md:')||/mangadex/i.test(media.provider||''))title.append(node('span','md-reader-attribution',`MangaDex · Grupo: ${chapter.group||'não informado'}`));
  const close=button('←','Fechar leitor',()=>{destroy();onClose?.();},'md-reader-button md-reader-close');
  toolbar.append(close,title);
  const mode=select([['webtoon','Rolagem'],['paged','Página']],preferences.readerMode,value=>{if(value==='paged'){scroller.stop();syncAutoRead();}preferences.readerMode=value;applyPreferences();savePreferences();scrollToPage(current);},'Modo de leitura');
  const direction=select([['ltr','Esquerda → direita'],['rtl','Direita → esquerda']],preferences.readerDirection,value=>{preferences.readerDirection=value;applyPreferences();savePreferences();},'Direção da leitura');
  const autoLabel=node('label','md-reader-toggle');const auto=node('input');auto.type='checkbox';auto.checked=preferences.autoTranslate!==false;autoLabel.append(auto,node('span','','Tradução automática'));
  auto.addEventListener('change',()=>{preferences.autoTranslate=auto.checked;if(!auto.checked){activeJob?.abort();cooldown.cancelRecovery();}else queueVisible();savePreferences();});
  const provider=select([['gemini','IA • balões (recomendado)'],['local','Básico • OCR local']],preferences.engine,value=>{preferences.engine=value;savePreferences();if(auto.checked)queueVisible();},'Motor de tradução');
  const controls=node('div','md-reader-controls');controls.append(mode,direction,autoLabel,provider);
  const translateButton=button('Traduzir','Traduzir a página atual',()=>queueRecord(records[current],true));
  const translateChapterButton=button('Traduzir capítulo','Traduzir todas as páginas do capítulo com IA',()=>{
    if(cooldown.blocked(true)){syncTranslationProgress();return;}
    cooldown.manual();
    if(!geminiAvailable){setNotice('A tradução de capítulo inteiro exige a IA configurada no servidor.');return;}
    preferences.engine='gemini';provider.value='gemini';savePreferences();
    setNotice(`Tradução completa iniciada: ${records.length} páginas. Você pode continuar lendo enquanto o capítulo é processado.`);
    for(const record of records)queueRecord(record,true);
  });
  translateChapterButton.disabled=true;
  const originalButton=button('Original','Alternar entre original e tradução',()=>{showOriginal=!showOriginal;originalButton.classList.toggle('is-active',showOriginal);records.forEach(displayRecord);});
  const compareButton=button('Comparar','Comparar original e tradução',()=>{compare=!compare;compareButton.classList.toggle('is-active',compare);records.forEach(displayRecord);});
  const editButton=button('Revisar','Revisar falas e áreas do balão',()=>openEditor(records[current]));
  const settingsButton=button('Ajustes','Preferências do leitor',()=>settingsPanel.hidden=!settingsPanel.hidden);
  const fullscreenButton=button('⛶','Tela cheia',async()=>{try{if(document.fullscreenElement===root)await document.exitFullscreen();else await root.requestFullscreen();}catch{setNotice('O navegador não permitiu a tela cheia.');}});
  controls.append(translateButton,translateChapterButton,originalButton,compareButton,editButton,settingsButton,fullscreenButton);toolbar.append(controls);
  const currentTranslation=node('div','md-current-translation'),currentTranslationStatus=node('span'),currentTranslationBar=node('progress','md-page-progress');currentTranslationStatus.setAttribute('role','status');currentTranslationStatus.setAttribute('aria-live','polite');currentTranslationBar.max=1;currentTranslationBar.value=0;currentTranslationBar.setAttribute('aria-label','Tradução da página atual');currentTranslation.hidden=true;currentTranslation.append(currentTranslationStatus,currentTranslationBar);controls.append(currentTranslation);
  const notice=node('div','md-reader-notice');notice.setAttribute('role','status');notice.hidden=true;
  const settingsPanel=node('div','md-reader-settings');settingsPanel.hidden=true;settingsPanel.append(node('h3','','Preferências do leitor'));
  function labelled(label,control){const element=node('label','md-reader-field');element.append(node('span','',label),control);settingsPanel.append(element);return element;}
  const target=select(LANGUAGE_OPTIONS.filter(([code])=>code!=='auto'&&code!=='ja-vert'),preferences.targetLanguage||'pt',value=>{preferences.targetLanguage=value;savePreferences();},'Idioma da tradução');labelled('Traduzir para',target);
  const source=select(LANGUAGE_OPTIONS,preferences.sourceLanguage,value=>{preferences.sourceLanguage=value;savePreferences();},'Idioma original');labelled('Idioma original',source);
  function range(label,key,min,max,step){const control=node('input');control.type='range';control.min=min;control.max=max;control.step=step;control.value=preferences[key];control.setAttribute('aria-label',label);const wrapper=node('div','md-reader-range');const value=node('output','',String(preferences[key]));wrapper.append(control,value);control.addEventListener('input',()=>{preferences[key]=Number(control.value);value.textContent=control.value;applyPreferences();savePreferences();});labelled(label,wrapper);return control;}
  range('Zoom (%)','readerZoom',50,180,5);range('Largura da leitura','readerWidth',480,1600,40);range('Tamanho da fonte de novel','readerFontSize',14,28,1);range('Tamanho das falas','fontScale',.6,1.8,.1);range('Confiança mínima','minConfidence',65,95,5);
  const font=select([['comic','Quadrinhos'],['sans','Sem serifa'],['serif','Serifa']],preferences.fontFamily,value=>{preferences.fontFamily=value;savePreferences();},'Fonte dos balões');labelled('Fonte das falas',font);
  const glossary=node('textarea','md-reader-glossary');glossary.rows=3;glossary.placeholder='Dragon = Dragão\nNome original = Nome preservado';glossary.maxLength=5000;glossary.value=preferences.glossary||'';glossary.addEventListener('change',()=>{preferences.glossary=glossary.value;savePreferences();});labelled('Glossário (um termo por linha)',glossary);
  for(const [key,label]of [['rememberCache','Guardar traduções neste navegador']]){const checkbox=node('input');checkbox.type='checkbox';checkbox.checked=!!preferences[key];checkbox.addEventListener('change',()=>{preferences[key]=checkbox.checked;savePreferences();});labelled(label,checkbox);}
  const cacheButton=button('Limpar traduções guardadas','Apagar cache local de imagens',async()=>{await clearTranslationCache().catch(()=>{});setNotice('O cache de traduções deste navegador foi apagado.');});settingsPanel.append(cacheButton,node('small','','Preferências locais; usuários conectados também podem sincronizá-las. A IA exige uma conta e está sujeita à cota diária.'));
  const counter=node('span','md-reader-counter'),slider=node('input','md-reader-slider');slider.type='range';slider.min=1;slider.max=Math.max(1,pages.length);slider.step=1;slider.value=current+1;slider.setAttribute('aria-label','Ir para uma página');slider.addEventListener('input',()=>scrollToPage(Number(slider.value)-1));
  const previous=button('‹','Página anterior',()=>stepPage(-1)),next=button('›','Próxima página',()=>{if(current===records.length-1){completed=true;updateChapterProgress(true);setNotice('Capítulo terminado.');}else stepPage(1);});
  const previousChapter=button('Capítulo anterior','Abrir capítulo anterior',()=>navigate(previousId));previousChapter.disabled=!previousId;
  const nextChapter=button('Próximo capítulo','Abrir próximo capítulo',()=>navigate(nextId));nextChapter.disabled=!nextId;
  const chapterProgress=node('progress','md-chapter-progress');chapterProgress.max=1;chapterProgress.value=0;chapterProgress.setAttribute('aria-label','Progresso de leitura do capítulo');const percentLabel=node('output','md-chapter-percent','0%'),readingProgress=node('div','md-chapter-meter');readingProgress.append(chapterProgress,percentLabel);
  footer.append(previousChapter,previous,counter,slider,next,nextChapter,readingProgress);
  const side=node('aside','md-autoread');side.setAttribute('aria-label','Leitura automática');const autoReadButton=button('▶','Ligar leitura automática',toggleAutoRead,'md-reader-button md-autoread-toggle');autoReadButton.setAttribute('aria-label','Ligar leitura automática');autoReadButton.setAttribute('aria-pressed','false');
  const autoReadPanel=node('div','md-autoread-panel');autoReadPanel.id=`md-speed-${crypto.randomUUID()}`;const autoReadStatus=node('span','md-autoread-status','Leitura automática desligada'),speed=node('input');speed.type='range';speed.min=8;speed.max=70;speed.step=1;speed.value=preferences.autoReadSpeed;speed.setAttribute('aria-label','Velocidade da leitura automática em pixels por segundo');const speedValue=node('output','',`${speed.value} px/s`);speed.addEventListener('input',()=>{preferences.autoReadSpeed=Number(speed.value);speedValue.textContent=`${speed.value} px/s`;savePreferences();});autoReadPanel.append(autoReadStatus,node('span','','Velocidade'),speed,speedValue);const speedButton=button('⚙','Ajustar velocidade da leitura automática',()=>{autoReadPanel.hidden=!autoReadPanel.hidden;speedButton.setAttribute('aria-expanded',String(!autoReadPanel.hidden));},'md-reader-button md-autoread-settings');speedButton.setAttribute('aria-label','Ajustar velocidade da leitura automática');speedButton.setAttribute('aria-controls',autoReadPanel.id);speedButton.setAttribute('aria-expanded','false');autoReadPanel.hidden=true;side.append(autoReadButton,speedButton,autoReadPanel);
  controls.append(side);root.append(toolbar,notice,settingsPanel,viewport,footer);container.replaceChildren(root);
  const records=pages.map((page,index)=>createRecord(page,index));
  const cooldown=createTranslationCooldown({onChange:()=>syncTranslationProgress(),onRetry:record=>{if(!destroyed&&record){record.failed=false;queueRecord(record,true,false,true);}}});
  const scroller=createAutoScroller({viewport,speed:()=>preferences.autoReadSpeed,hold:()=>autoReadHold(),onFrame:()=>updateChapterProgress(),onEnd:()=>{completed=true;syncAutoRead();updateChapterProgress(true);setNotice('Capítulo terminado.');}});
  function autoReadHold(){if(!booted||destroyed||reviewing||editor||document.hidden||!records.length||records.some(record=>record.renderPending))return true;const bounds=viewport.getBoundingClientRect(),visible=records.filter(record=>{const box=record.element.getBoundingClientRect();return !record.element.hidden&&box.bottom>bounds.top&&box.top<bounds.top+viewport.clientHeight;});if(viewport.scrollTop>=viewport.scrollHeight-viewport.clientHeight-1){const last=records.at(-1);if(last.element.getBoundingClientRect().bottom>bounds.top+viewport.clientHeight+2||!last.paragraphs&&!last.image.complete&&!last.imageFailed)return true;}return (visible.length?visible:[records[current]]).some(record=>!record.paragraphs&&!record.image.complete&&!record.imageFailed||preferences.autoTranslate&&nonPortuguese(chapter.language)&&!record.result&&!record.translatedTexts&&!record.failed);}
  function syncAutoRead(){const running=scroller.running;autoReadButton.textContent=running?'Ⅱ':'▶';autoReadButton.title=running?'Parar leitura automática':'Ligar leitura automática';autoReadButton.setAttribute('aria-label',autoReadButton.title);autoReadButton.setAttribute('aria-pressed',String(running));autoReadStatus.textContent=running?'Leitura automática ligada':'Leitura automática desligada';root.classList.toggle('is-autoreading',running);}
  function toggleAutoRead(){if(scroller.running)scroller.stop();else{if(preferences.readerMode==='paged'){preferences.readerMode='webtoon';mode.value='webtoon';applyPreferences();scrollToPage(current,false);savePreferences();setNotice('Leitura automática ativada no modo Rolagem.');}completed=false;queueVisible();scroller.start();}syncAutoRead();}
  if(!records.length){const empty=node('div','md-reader-empty','Este capítulo não possui páginas disponíveis para leitura.');if(chapter.externalUrl){try{const external=new URL(chapter.externalUrl);if(external.protocol==='https:'&&!external.username&&!external.password){const link=node('a','md-reader-button','Abrir na fonte');link.href=external.href;link.target='_blank';link.rel='noopener noreferrer';empty.append(node('p'),link);}}catch{}}content.append(empty);}
  const observer=new IntersectionObserver(entries=>{
    for(const entry of entries){const record=records[Number(entry.target.dataset.pageIndex)];if(!record)continue;record.visible=entry.isIntersecting;if(entry.isIntersecting){if(preferences.readerMode==='webtoon'&&entry.intersectionRatio>.2)setCurrent(record.index);if(booted&&preferences.autoTranslate&&nonPortuguese(chapter.language))queueRecord(record);}}
  },{root:viewport,rootMargin:'240px 0px',threshold:[0,.2,.5,.8]});
  records.forEach(record=>observer.observe(record.element));
  viewport.addEventListener('scroll',()=>{if(preferences.readerMode==='webtoon'){const top=viewport.getBoundingClientRect().top+viewport.clientHeight*.3;let chosen=current,distance=Infinity;for(const record of records){const box=record.element.getBoundingClientRect();const candidate=top>=box.top&&top<=box.bottom?0:Math.min(Math.abs(top-box.top),Math.abs(top-box.bottom));if(candidate<distance){chosen=record.index;distance=candidate;}}setCurrent(chosen);}updateChapterProgress();});
  document.addEventListener('keydown',keyboard);
  applyPreferences();setCurrent(current);root.focus({preventScroll:true});
  (async()=>{
    const result=await Promise.allSettled([api?.('/api/config'),api?.('/api/settings')]);
    if(destroyed)return;
    const config=result[0].status==='fulfilled'?result[0].value:null;geminiAvailable=!!config?.translation?.gemini;
    const saved=result[1].status==='fulfilled'?result[1].value?.settings:null;
    if(saved){for(const key of Object.keys(INITIAL))if(saved[key]!==undefined)preferences[key]=saved[key];auto.checked=preferences.autoTranslate!==false;mode.value=preferences.readerMode;direction.value=preferences.readerDirection;source.value=preferences.sourceLanguage;target.value=preferences.targetLanguage;provider.value=preferences.engine;applyPreferences();}
    provider.querySelector('option[value="gemini"]').disabled=!geminiAvailable;translateChapterButton.disabled=!geminiAvailable;if(!geminiAvailable&&preferences.engine==='gemini'){preferences.engine='local';provider.value='local';}
    speed.value=preferences.autoReadSpeed;speedValue.textContent=`${speed.value} px/s`;booted=true;scrollToPage(current,false);queueVisible();
  })().catch(()=>{booted=true;queueVisible();});

  function createRecord(page,index){
    const element=node('article','md-page');element.dataset.pageIndex=String(index);const label=node('div','md-page-label',`Página ${index+1}`);const progress=node('div','md-page-status','');progress.setAttribute('role','status');progress.setAttribute('aria-live','polite');const bar=node('progress','md-page-progress');bar.max=1;bar.value=0;bar.hidden=true;bar.setAttribute('aria-label',`Tradução da página ${index+1}`);
    const images=node('div','md-page-comparison'),originalLabel=node('span','md-page-original-label','ORIGINAL'),translatedLabel=node('span','md-page-translated-label','TRADUÇÃO');
    const record={page,index,element,progress,bar,lastAnnouncement:0,visible:false,queued:false,working:false,originalDataUrl:null,originalPromise:null,result:null,translatedTexts:null,paragraphs:typeof page.text==='string'?splitNovelText(page.text):null};
    if(record.paragraphs){element.classList.add('md-novel-page');record.originalElement=node('div','md-novel-original');record.translatedElement=node('div','md-novel-translated');record.originalElement.append(originalLabel);record.translatedElement.append(translatedLabel);images.append(record.originalElement,record.translatedElement);displayNovel(record);}
    else{record.originalImage=node('img','md-original-image');record.originalImage.alt=`Original — página ${index+1}`;record.originalImage.loading='lazy';record.originalImage.decoding='async';record.originalImage.src=page.url||'';record.image=node('img','md-page-image');record.image.alt=`${media.title} — página ${index+1}`;record.image.loading='lazy';record.image.decoding='async';record.image.src=page.url||'';record.image.addEventListener('load',()=>{if(record.image.naturalWidth){element.style.setProperty('--md-page-ratio',String(record.image.naturalWidth/record.image.naturalHeight));}});record.image.addEventListener('error',()=>{if(!destroyed){progress.textContent='Não foi possível carregar esta página.';element.classList.add('has-error');}});const originalWrap=node('div','md-original-wrap'),translatedWrap=node('div','md-translated-wrap');originalWrap.append(originalLabel,record.originalImage);translatedWrap.append(translatedLabel,record.image);images.append(originalWrap,translatedWrap);}
    const actions=node('div','md-page-actions');actions.append(button('Traduzir página','Traduzir esta página',()=>queueRecord(record,true)),button('Revisar','Editar os blocos desta página',()=>openEditor(record)),button('Tentar novamente','Repetir leitura e tradução sem usar o cache',()=>queueRecord(record,true,true)));
    record.image?.addEventListener('error',()=>{record.imageFailed=true;record.renderPending=false;});record.image?.addEventListener('load',()=>{record.renderPending=false;updateChapterProgress();});element.append(label,images,bar,progress,actions);content.append(element);displayRecord(record);return record;
  }
  function setNotice(message){notice.textContent=message;notice.hidden=!message;}
  function syncTranslationProgress(){const wait=cooldown?.state,record=records[current];translateButton.disabled=!!wait?.remaining;translateChapterButton.disabled=!geminiAvailable||!!wait?.remaining;if(wait){currentTranslation.hidden=false;currentTranslationBar.hidden=true;let text;if(wait.daily){const reset=new Date(wait.until);text=`Cota de tradução atingida. Liberação prevista: ${reset.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}. A arte original continua disponível.`;}else if(wait.remaining){text=`Tradução pausada · tente novamente em ${Math.ceil(wait.remaining/1000)}s.${wait.recover?' Esta página terá uma nova tentativa.':''}`;}else text='A espera terminou. Use Traduzir para tentar esta página novamente.';if(currentTranslationStatus.textContent!==text)currentTranslationStatus.textContent=text;return;}currentTranslation.hidden=!record?.progress.textContent;if(!record)return;const text=`Página ${current+1} · ${record.progress.textContent}`;if(currentTranslationStatus.textContent!==text)currentTranslationStatus.textContent=text;currentTranslationBar.value=record.bar.value;currentTranslationBar.hidden=record.bar.hidden;}
  function updateChapterProgress(flush=false){if(!records.length)return;const percent=chapterPercent({mode:preferences.readerMode,page:current,total:records.length,top:viewport.scrollTop,height:viewport.scrollHeight,view:viewport.clientHeight,completed});chapterProgress.value=percent/100;percentLabel.textContent=`${Math.floor(percent)}%`;chapterProgress.setAttribute('aria-valuetext',`${Math.floor(percent)}% do capítulo`);const save=()=>{lastProgressSave=Date.now();progressTimer=null;const result=onProgress?.({mediaId:media.id,chapterId:chapter.id,page:current+1,totalPages:records.length,percent:Math.round(percent)});result?.catch?.(()=>{});};if(flush||Date.now()-lastProgressSave>=1000){clearTimeout(progressTimer);save();}else if(!progressTimer)progressTimer=setTimeout(()=>updateChapterProgress(true),1000-(Date.now()-lastProgressSave));}
  function setCurrent(index){if(!records.length)return;current=Math.max(0,Math.min(records.length-1,index));counter.textContent=`${current+1} / ${records.length}`;slider.value=current+1;previous.disabled=current===0&&!previousId;next.disabled=false;next.textContent=current===records.length-1?'✓':'›';next.title=current===records.length-1?'Concluir capítulo':'Próxima página';next.setAttribute('aria-label',next.title);if(preferences.readerMode==='paged')records.forEach(record=>record.element.hidden=record.index!==current);syncTranslationProgress();updateChapterProgress();}
  function scrollToPage(index,smooth=true){if(!records.length)return;completed=false;setCurrent(index);const record=records[current];if(preferences.readerMode==='webtoon')record.element.scrollIntoView({behavior:smooth?'smooth':'auto',block:'start'});else viewport.scrollTop=0;updateChapterProgress();if(booted&&preferences.autoTranslate&&nonPortuguese(chapter.language))queueRecord(record);}
  function stepPage(amount){if(current+amount<0)return previousId?navigate(previousId):null;if(current+amount>=records.length)return nextId?navigate(nextId):null;scrollToPage(current+amount);}
  function navigate(id){if(!id)return;destroy();onNavigate?.(id);}
  function applyPreferences(){root.dataset.mode=preferences.readerMode;root.dataset.direction=preferences.readerDirection;root.style.setProperty('--md-content-width',`${Math.min(Math.max(320,preferences.readerWidth),1600)*Math.max(.5,Math.min(1.8,preferences.readerZoom/100))}px`);root.style.setProperty('--md-novel-font-size',`${Math.max(14,Math.min(28,preferences.readerFontSize))}px`);root.classList.toggle('is-zoomed',preferences.readerZoom>100);if(records?.length)records.forEach(record=>record.element.hidden=preferences.readerMode==='paged'&&record.index!==current);}
  function savePreferences(){try{localStorage.setItem(PREFERENCE_KEY,JSON.stringify(preferences));}catch{}clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(!destroyed)api?.('/api/settings',{method:'POST',body:{settings:preferences}})?.catch?.(()=>{});},800);}
  function queueVisible(){if(!booted||!preferences.autoTranslate||!nonPortuguese(chapter.language)||cooldown.blocked())return;for(const record of records)if(record.visible||record.index===current&&preferences.readerMode==='paged')queueRecord(record);}
  async function originalData(record){
    if(record.originalDataUrl)return record.originalDataUrl;
    if(!record.originalPromise)record.originalPromise=(async()=>{const response=await fetch(record.page.url,{signal:lifetime.signal,credentials:'same-origin',cache:'force-cache'});if(!response.ok)throw new Error(`Esta página não está disponível (${response.status}).`);const blob=await response.blob();if(blob.size>65*1024*1024)throw new Error('A página é grande demais. Use uma imagem menor.');const dataUrl=await blobDataURL(blob,lifetime.signal);if(!/^data:image\//.test(dataUrl))throw new Error('O arquivo não contém uma imagem legível.');record.originalDataUrl=dataUrl;return dataUrl;})().catch(error=>{record.originalPromise=null;throw error;});
    return record.originalPromise;
  }
  function queueRecord(record,force=false,refresh=false,recovery=false){
    if(!record||destroyed||record.queued||record.working||(!force&&(record.result||record.translatedTexts||record.failed)))return;
    if(cooldown.blocked(force)){syncTranslationProgress();return;}
    if(force&&!recovery)cooldown.manual();
    record.queued=true;record.progress.textContent='Aguardando tradução';record.bar.value=0;record.bar.hidden=false;record.element.classList.add('is-pending');syncTranslationProgress();
    busy=busy.catch(()=>{}).then(async()=>{
      record.queued=false;if(destroyed||cooldown.blocked()||!force&&(!preferences.autoTranslate||!record.visible&&!(record.index===current&&preferences.readerMode==='paged'))){record.progress.textContent='';record.bar.hidden=true;record.element.classList.remove('is-pending');return;}
      record.working=true;const job=new AbortController();activeJob=job;const stop=()=>job.abort();lifetime.signal.addEventListener('abort',stop,{once:true});
      try{
        const onProgress=event=>{if(destroyed)return;const value=Math.max(0,Math.min(1,Number(event.progress)||0));record.bar.value=value;const now=Date.now();if(now-record.lastAnnouncement>=600||value===1){record.lastAnnouncement=now;record.progress.textContent=`${event.status||'Traduzindo'} · ${Math.round(value*100)}%`;}syncTranslationProgress();};
        const settings={...preferences};if(refresh)settings.rememberCache=false;if(settings.sourceLanguage==='auto'&&chapter.language&&chapter.language!=='auto'){const hint=String(chapter.language).toLowerCase();const known={en:'en',ja:'ja',ko:'ko',zh:'zh-CN','zh-hk':'zh-TW',es:'es',fr:'fr',de:'de',it:'it',ru:'ru',ar:'ar',pt:'pt','pt-br':'pt'};settings.sourceLanguage=known[hint]||'auto';}
        if(record.paragraphs){const result=await translateCopy(record.paragraphs,settings,{onProgress,signal:job.signal});record.translatedTexts=result.translations.map(item=>item.text);record.warnings=result.warnings;record.usedEngine=['google','cloudflare'].includes(result.usedProvider)||['google','cloudflare'].includes(result.provider)?'local':settings.engine;}
        else record.result=await translatePage(await originalData(record),settings,{onProgress,signal:job.signal});
        if(destroyed||job.signal.aborted)return;record.failed=false;record.bar.value=1;const basic=record.result?.usedEngine==='local'||record.usedEngine==='local';record.progress.textContent=basic?'Traduzido pelo modo básico':'Traduzido';record.element.classList.remove('has-error');displayRecord(record);
        const warnings=record.result?.warnings||record.warnings;if(warnings?.length){record.progress.title=warnings.join('\n');if(!basic)record.progress.textContent='Traduzido · revisão disponível';}
      }catch(error){if(!destroyed){if(error.name==='AbortError')record.progress.textContent='Tradução cancelada';else{record.failed=true;record.element.classList.add('has-error');record.progress.textContent=error.message||'Não foi possível traduzir esta página.';cooldown.pause(error,record);}}}
      finally{record.working=false;if(record.failed||job.signal.aborted)record.bar.hidden=true;record.element.classList.remove('is-pending');lifetime.signal.removeEventListener('abort',stop);if(activeJob===job)activeJob=null;syncTranslationProgress();}
    });
  }
  function displayNovel(record){
    record.originalElement.replaceChildren(node('span','md-page-original-label','ORIGINAL'));record.translatedElement.replaceChildren(node('span','md-page-translated-label','TRADUÇÃO'));
    record.paragraphs.forEach((text,index)=>{const originalParagraph=node('p','',text),translatedParagraph=node('p','',record.translatedTexts?.[index]||text);record.originalElement.append(originalParagraph);record.translatedElement.append(translatedParagraph);});
  }
  function displayRecord(record){
    record.element.classList.toggle('is-comparing',compare&&!!(record.result||record.translatedTexts));record.element.classList.toggle('show-original',showOriginal);
    if(record.paragraphs)displayNovel(record);else{const nextSource=showOriginal?record.originalDataUrl||record.page.url:record.result?.dataUrl||record.page.url;if(record.image.getAttribute('src')!==nextSource){record.renderPending=true;record.image.src=nextSource;}const originalSource=record.originalDataUrl||record.page.url;if(record.originalImage.getAttribute('src')!==originalSource)record.originalImage.src=originalSource;if(record.result?.width&&record.result?.height)record.element.style.setProperty('--md-page-ratio',String(record.result.width/record.result.height));}
  }
  function keyboard(event){
    if(destroyed||editor?.open||event.ctrlKey||event.metaKey||event.altKey||/^(INPUT|TEXTAREA|SELECT|BUTTON)$/.test(event.target?.tagName)||event.target?.isContentEditable)return;
    const key=event.key;if(['ArrowRight','ArrowLeft','PageDown','PageUp','Home','End',' ','Escape'].includes(key))event.preventDefault();
    if(key==='Escape'){destroy();onClose?.();}else if(key==='ArrowRight')stepPage(preferences.readerDirection==='rtl'?-1:1);else if(key==='ArrowLeft')stepPage(preferences.readerDirection==='rtl'?1:-1);else if(key==='Home')scrollToPage(0);else if(key==='End')scrollToPage(records.length-1);else if(key==='PageDown'||key===' '){if(preferences.readerMode==='webtoon')viewport.scrollBy({top:viewport.clientHeight*.85,behavior:'smooth'});else stepPage(1);}else if(key==='PageUp'){if(preferences.readerMode==='webtoon')viewport.scrollBy({top:-viewport.clientHeight*.85,behavior:'smooth'});else stepPage(-1);}else if(key.toLowerCase()==='o')originalButton.click();else if(key.toLowerCase()==='t')translateButton.click();else if(key.toLowerCase()==='e')editButton.click();else if(key.toLowerCase()==='f')fullscreenButton.click();
  }
  async function openEditor(record){
    if(!record||destroyed)return;if(record.working){setNotice('Aguarde a tradução desta página para revisar os blocos.');return;}
    reviewing=true;try{
      if(!record.paragraphs&&!record.result){setNotice('Desenhe uma área, informe o texto original e use “Traduzir este bloco” para revisar uma fala não detectada.');record.result=await renderImage(await originalData(record),[],preferences,{signal:lifetime.signal});if(destroyed)return;}
      editor=node('dialog','md-reader-editor');const dialog=editor,heading=node('h2','',`Revisar página ${record.index+1}`),layout=node('div','md-editor-layout'),form=node('div','md-editor-form'),errorBox=node('p','md-editor-error'),actions=node('div','md-editor-actions');
      dialog.append(heading,layout,errorBox,actions);root.append(dialog);
      const blocks=record.paragraphs?record.paragraphs.map((text,index)=>({id:`paragraph-${index}`,text,translated:record.translatedTexts?.[index]||text})):structuredClone(record.result.blocks);
      let selected=0,draw=false,drag=null;const blockSelect=select([],null,()=>{storeCurrent();selected=Number(blockSelect.value);loadCurrent();},'Bloco para revisar');
      const originalText=node('textarea'),translatedText=node('textarea');originalText.rows=5;translatedText.rows=5;originalText.maxLength=10000;translatedText.maxLength=18000;const sourceField=node('label','md-editor-field');sourceField.append(node('span','','Texto original'),originalText);const translatedField=node('label','md-editor-field');translatedField.append(node('span','','Tradução'),translatedText);form.append(blockSelect,sourceField,translatedField);
      const coordinates={};let preview,overlay,width,height;
      if(!record.paragraphs){const frame=node('div','md-editor-image');preview=node('img');preview.src=await originalData(record);preview.alt='Página original para revisar as áreas';overlay=node('div','md-editor-overlay');frame.append(preview,overlay);layout.append(frame);width=record.result.width;height=record.result.height;const fields=node('div','md-editor-coordinates');for(const key of ['x','y','w','h']){const label=node('label','',key.toUpperCase()),input=node('input');input.type='number';input.step=1;input.min=key==='w'||key==='h'?1:0;input.max=key==='x'||key==='w'?width:height;input.addEventListener('input',()=>{storeCurrent();drawBoxes();});coordinates[key]=input;label.append(input);fields.append(label);}form.append(fields);
        const drawButton=button('Desenhar novo balão','Selecionar uma área manualmente',()=>{draw=!draw;frame.classList.toggle('is-drawing',draw);drawButton.classList.toggle('is-active',draw);});form.append(drawButton,button('Remover bloco','Restaurar original nesta área',()=>{blocks.splice(selected,1);selected=Math.max(0,Math.min(blocks.length-1,selected));refreshSelect();loadCurrent();}));
        frame.addEventListener('pointerdown',event=>{if(!draw)return;const box=preview.getBoundingClientRect();drag={x:Math.max(0,event.clientX-box.left),y:Math.max(0,event.clientY-box.top),box};frame.setPointerCapture(event.pointerId);});
        frame.addEventListener('pointerup',event=>{if(!drag)return;const x=Math.max(0,Math.min(drag.box.width,event.clientX-drag.box.left)),y=Math.max(0,Math.min(drag.box.height,event.clientY-drag.box.top)),box={x:Math.min(drag.x,x)/drag.box.width*width,y:Math.min(drag.y,y)/drag.box.height*height,w:Math.abs(x-drag.x)/drag.box.width*width,h:Math.abs(y-drag.y)/drag.box.height*height};drag=null;if(box.w<5||box.h<5)return;storeCurrent();blocks.push({id:`manual-${crypto.randomUUID()}`,text:'',translated:'',confidence:100,sourceLanguage:preferences.sourceLanguage,box,cleanupBoxes:[{...box}]});selected=blocks.length-1;draw=false;frame.classList.remove('is-drawing');drawButton.classList.remove('is-active');refreshSelect();loadCurrent();});
      }
      layout.append(form);
      form.append(button('Traduzir este bloco','Traduzir o texto original corrigido',async()=>{storeCurrent();if(!blocks[selected]?.text.trim())return;if(cooldown.blocked(true)){errorBox.textContent='A tradução está aguardando liberação. Acompanhe o prazo na barra do leitor.';syncTranslationProgress();return;}cooldown.manual();try{errorBox.textContent='Traduzindo bloco…';const result=await translateCopy([blocks[selected].text],preferences,{signal:lifetime.signal});blocks[selected].translated=result.translations[0].text;translatedText.value=blocks[selected].translated;errorBox.textContent='';}catch(error){errorBox.textContent=error.message;cooldown.pause(error,record,false);}}));
      const apply=button('Aplicar revisão','Apagar o original e compor a revisão',async()=>{storeCurrent();apply.disabled=true;try{if(record.paragraphs){record.translatedTexts=blocks.map(block=>block.translated);record.paragraphs=blocks.map(block=>block.text);}else{record.result=await renderImage(await originalData(record),blocks,preferences,{signal:lifetime.signal});}if(destroyed)return;displayRecord(record);record.progress.textContent='Revisão aplicada';dialog.close();dialog.remove();if(editor===dialog)editor=null;}catch(error){errorBox.textContent=error.message;}finally{apply.disabled=false;}});
      actions.append(button('Cancelar','Fechar sem aplicar',()=>{dialog.close();dialog.remove();if(editor===dialog)editor=null;}),apply);dialog.addEventListener('cancel',()=>{dialog.remove();if(editor===dialog)editor=null;});
      function storeCurrent(){const block=blocks[selected];if(!block)return;block.text=originalText.value;block.translated=translatedText.value;if(block.box)for(const key of ['x','y','w','h']){const value=Number(coordinates[key].value);if(Number.isFinite(value))block.box[key]=value;}}
      function refreshSelect(){blockSelect.replaceChildren();blocks.forEach((block,index)=>{const option=node('option','',`${index+1} · ${block.text.slice(0,45)||'Novo balão'}`);option.value=index;blockSelect.append(option);});blockSelect.value=String(selected);}
      function drawBoxes(){if(!overlay)return;overlay.replaceChildren();blocks.forEach((block,index)=>{if(!block.box)return;const rectangle=node('button',`md-editor-box${index===selected?' is-selected':''}`);rectangle.type='button';rectangle.textContent=String(index+1);rectangle.style.left=`${block.box.x/width*100}%`;rectangle.style.top=`${block.box.y/height*100}%`;rectangle.style.width=`${block.box.w/width*100}%`;rectangle.style.height=`${block.box.h/height*100}%`;rectangle.addEventListener('click',event=>{event.stopPropagation();if(draw)return;storeCurrent();selected=index;blockSelect.value=String(index);loadCurrent();});overlay.append(rectangle);});}
      function loadCurrent(){const block=blocks[selected];originalText.value=block?.text||'';translatedText.value=block?.translated||'';originalText.disabled=translatedText.disabled=!block;if(block?.box)for(const key of ['x','y','w','h'])coordinates[key].value=Math.round(block.box[key]);drawBoxes();}
      refreshSelect();loadCurrent();if(destroyed){dialog.remove();editor=null;return;}dialog.showModal();
    }catch(error){setNotice(error.message||'Não foi possível abrir o editor.');editor?.remove();editor=null;}finally{reviewing=false;}
  }
  function destroy(){if(destroyed)return;updateChapterProgress(true);scroller.stop();destroyed=true;cooldown.destroy();lifetime.abort();activeJob?.abort();observer.disconnect();document.removeEventListener('keydown',keyboard);clearTimeout(saveTimer);clearTimeout(progressTimer);editor?.remove();if(document.fullscreenElement===root)document.exitFullscreen().catch(()=>{});root.remove();}
  return {destroy};
}
